package com.example.demo.entity;

import java.math.BigDecimal;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.stock
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private String stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img1
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private String img1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img2
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private String img2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img3
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private String img3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img4
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    private String img4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.stock
     *
     * @return the value of goods.stock
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.stock
     *
     * @param stock the value for goods.stock
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img1
     *
     * @return the value of goods.img1
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public String getImg1() {
        return img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img1
     *
     * @param img1 the value for goods.img1
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setImg1(String img1) {
        this.img1 = img1 == null ? null : img1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img2
     *
     * @return the value of goods.img2
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public String getImg2() {
        return img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img2
     *
     * @param img2 the value for goods.img2
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setImg2(String img2) {
        this.img2 = img2 == null ? null : img2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img3
     *
     * @return the value of goods.img3
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public String getImg3() {
        return img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img3
     *
     * @param img3 the value for goods.img3
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setImg3(String img3) {
        this.img3 = img3 == null ? null : img3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img4
     *
     * @return the value of goods.img4
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public String getImg4() {
        return img4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img4
     *
     * @param img4 the value for goods.img4
     *
     * @mbggenerated Wed May 22 18:20:39 CST 2019
     */
    public void setImg4(String img4) {
        this.img4 = img4 == null ? null : img4.trim();
    }
}